In [1]:
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, confusion_matrix, recall_score,\
accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

import prepare

In [2]:
df = prepare.wrangle()
train, validate, test = prepare.split_data(df)

opening data from file


In [3]:
train.churn.value_counts()

0    2897
1    1046
Name: churn, dtype: int64

Our baseline prediction will be that a customer will not churn (churn = 0)

In [4]:
baseline = [0] * len(train)

In [5]:
len(baseline) == len(train)

True

In [6]:
print(f'The baseline prediction score accuracy is: {(train.churn == baseline).mean():.2%}')

The baseline prediction score accuracy is: 73.47%


In [7]:
internet = train[train['internet_service_type_none'] == 0]
internet

customer_id  gender  senior_citizen  partner  dependents  tenure  \
5717  8050-XGRVL  Female               0        1           1      62   
1083  1576-PFZIW    Male               1        1           0      70   
2475  3541-ZNUHK  Female               0        1           1      55   
2350  3370-GQEAL    Male               0        1           1      30   
2393  3422-LYEPQ    Male               0        1           1       1   
...          ...     ...             ...      ...         ...     ...   
4128  5839-SUYVZ    Male               0        0           0      16   
731   1078-TDCRN  Female               1        1           0       3   
2272  3249-VHRIP  Female               0        0           0      62   
6629  9419-IPPBE  Female               0        1           1      51   
5563  7838-LAZFO    Male               0        1           0      45   

      phone_service    multiple_lines online_security online_backup  ...  \
5717              1                No             Yes            No  ...   
1083              1                No             Yes           Yes  ...   
2475              1               Yes             Yes           Yes  ...   
2350              1               Yes              No            No  ...   
2393              1                No              No            No  ...   
...             ...               ...             ...           ...  ...   
4128              1                No              No            No  ...   
731               0  No phone service              No           Yes  ...   
2272              0  No phone service              No           Yes  ...   
6629              1               Yes              No            No  ...   
5563              1                No             Yes           Yes  ...   

     streaming_movies_no_internet_service streaming_movies_yes  \
5717                                    0                    0   
1083                                    0                    1   
2475                                    0                    0   
2350                                    0                    0   
2393                                    0                    0   
...                                   ...                  ...   
4128                                    0                    0   
731                                     0                    0   
2272                                    0                    1   
6629                                    0                    1   
5563                                    0                    1   

     contract_type_one_year contract_type_two_year  \
5717                      1                      0   
1083                      0                      1   
2475                      0                      0   
2350                      0                      0   
2393                      0                      0   
...                     ...                    ...   
4128                      0                      0   
731                       0                      0   
2272                      0                      1   
6629                      1                      0   
5563                      1                      0   

      internet_service_type_fiber_optic  internet_service_type_none  \
5717                                  0                           0   
1083                                  1                           0   
2475                                  1                           0   
2350                                  1                           0   
2393                                  1                           0   
...                                 ...                         ...   
4128                                  1                           0   
731                                   0                           0   
2272                                  0                           0   
6629                                  1                        

In [8]:
train.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'paperless_billing', 'monthly_charges',
       'total_charges', 'churn', 'contract_type', 'internet_service_type',
       'payment_type', 'gender_male', 'multiple_lines_no_phone_service',
       'multiple_lines_yes', 'online_security_no_internet_service',
       'online_security_yes', 'online_backup_no_internet_service',
       'online_backup_yes', 'device_protection_no_internet_service',
       'device_protection_yes', 'tech_support_no_internet_service',
       'tech_support_yes', 'streaming_tv_no_internet_service',
       'streaming_tv_yes', 'streaming_movies_no_internet_service',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_non

In [9]:
X_cols_a = ['gender_male', 'online_security_no_internet_service',
     'online_security_yes', 'online_backup_no_internet_service',
     'online_backup_yes', 'device_protection_no_internet_service',
     'device_protection_yes', 'tech_support_no_internet_service',
     'tech_support_yes']
y_col='churn'

In [10]:
# make the decision tree object
dt_1 = DecisionTreeClassifier()
# fit the data to the dt object
dt_1.fit(train[X_cols_a], train[y_col])
# predict with the dt object
dt_1_preds = dt_1.predict(train[X_cols_a])

print(classification_report(train[y_col], dt_1_preds))
print()
print(confusion_matrix(train[y_col], dt_1_preds))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84      2897
           1       0.56      0.38      0.45      1046

    accuracy                           0.76      3943
   macro avg       0.68      0.64      0.65      3943
weighted avg       0.74      0.76      0.74      3943


[[2588  309]
 [ 650  396]]


In [11]:
# create the random forest classifier object
rf_1 = RandomForestClassifier()
# fit the rf object
rf_1.fit(train[X_cols_a], train[y_col])
# predict with the rf object
rf_1_preds = rf_1.predict(train[X_cols_a])

print(classification_report(train[y_col], rf_1_preds))
print()
print(confusion_matrix(train[y_col], rf_1_preds))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84      2897
           1       0.56      0.38      0.45      1046

    accuracy                           0.76      3943
   macro avg       0.68      0.64      0.65      3943
weighted avg       0.74      0.76      0.74      3943


[[2588  309]
 [ 650  396]]


In [12]:
# create the K_Nearest_Neighbors object
knn_1 = KNeighborsClassifier()
# fit the KNN object
knn_1.fit(train[X_cols_a], train[y_col])
# predict with the knn object
knn_1_preds = knn_1.predict(train[X_cols_a])

print(classification_report(train[y_col], knn_1_preds))
print()
print(confusion_matrix(train[y_col], knn_1_preds))

              precision    recall  f1-score   support

           0       0.76      0.90      0.82      2897
           1       0.41      0.19      0.26      1046

    accuracy                           0.71      3943
   macro avg       0.58      0.55      0.54      3943
weighted avg       0.66      0.71      0.67      3943


[[2614  283]
 [ 846  200]]


/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [13]:
# create the logistic regression object
lr_1 = LogisticRegression()
# fit the lr object
lr_1.fit(train[X_cols_a], train[y_col])
# predict with the lr object
lr_1_preds = lr_1.predict(train[X_cols_a])

print(classification_report(train[y_col], lr_1_preds))
print()
print(confusion_matrix(train[y_col], lr_1_preds))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84      2897
           1       0.56      0.38      0.45      1046

    accuracy                           0.76      3943
   macro avg       0.68      0.64      0.65      3943
weighted avg       0.74      0.76      0.74      3943


[[2588  309]
 [ 650  396]]


In [14]:
train['security_and_backup'] = ((train.online_backup == 'Yes') 
                                   & (train.online_security == 'Yes'))
validate['security_and_backup'] = ((validate.online_backup == 'Yes') 
                                   & (validate.online_security == 'Yes'))
test['security_and_backup'] = ((test.online_backup == 'Yes') 
                                   & (test.online_security == 'Yes'))

In [15]:
train['protection_and_tech'] = ((train.device_protection_yes == 1) 
                        & train.tech_support_yes == 1)
validate['protection_and_tech'] = ((validate.device_protection_yes == 1) 
                        & validate.tech_support_yes == 1)
test['protection_and_tech'] = ((test.device_protection_yes == 1) 
                        & test.tech_support_yes == 1)

In [16]:
X_cols_b = ['gender_male', 'online_security_no_internet_service',
       'online_security_yes', 'online_backup_no_internet_service',
       'online_backup_yes', 'device_protection_no_internet_service',
       'device_protection_yes', 'tech_support_no_internet_service',
       'tech_support_yes', 'security_and_backup', 'protection_and_tech', 
       'internet_service_type_fiber_optic', 'internet_service_type_none']

In [17]:
# make the decision tree object
dt_2 = DecisionTreeClassifier()
# fit the data to the dt object
dt_2.fit(train[X_cols_b], train[y_col])
# predict with the dt object
dt_2_preds = dt_2.predict(train[X_cols_b])

In [18]:
print(classification_report(train[y_col], dt_2_preds))
print()
print(confusion_matrix(train[y_col], dt_2_preds))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86      2897
           1       0.63      0.34      0.44      1046

    accuracy                           0.77      3943
   macro avg       0.71      0.63      0.65      3943
weighted avg       0.75      0.77      0.75      3943


[[2689  208]
 [ 690  356]]


In [19]:
# create the random forest classifier object
rf_2 = RandomForestClassifier()
# fit the rf object
rf_2.fit(train[X_cols_b], train[y_col])
# predict with the rf object
rf_2_preds = rf_2.predict(train[X_cols_b])

In [20]:
print(classification_report(train[y_col], rf_2_preds))
print()
print(confusion_matrix(train[y_col], rf_2_preds))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85      2897
           1       0.61      0.38      0.47      1046

    accuracy                           0.77      3943
   macro avg       0.71      0.65      0.66      3943
weighted avg       0.75      0.77      0.75      3943


[[2646  251]
 [ 647  399]]


In [21]:
# create the K_Nearest_Neighbors object
knn_2 = KNeighborsClassifier()
# fit the KNN object
knn_2.fit(train[X_cols_b], train[y_col])
# predict with the knn object
knn_2_preds = knn_2.predict(train[X_cols_b])

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [22]:
print(classification_report(train[y_col], knn_2_preds))
print()
print(confusion_matrix(train[y_col], knn_2_preds))

              precision    recall  f1-score   support

           0       0.79      0.87      0.83      2897
           1       0.49      0.36      0.42      1046

    accuracy                           0.73      3943
   macro avg       0.64      0.61      0.62      3943
weighted avg       0.71      0.73      0.72      3943


[[2514  383]
 [ 671  375]]


In [23]:
# create the logistic regression object
lr_2 = LogisticRegression()
# fit the lr object
lr_2.fit(train[X_cols_b], train[y_col])
# predict with the lr object
lr_2_preds = lr_2.predict(train[X_cols_b])

In [24]:
print(classification_report(train[y_col], lr_2_preds))
print()
print(confusion_matrix(train[y_col], lr_2_preds))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85      2897
           1       0.61      0.38      0.47      1046

    accuracy                           0.77      3943
   macro avg       0.71      0.65      0.66      3943
weighted avg       0.75      0.77      0.75      3943


[[2646  251]
 [ 647  399]]


In [25]:
X_cols_c = ['dependents', 'streaming_tv_no_internet_service',
       'streaming_tv_yes', 'streaming_movies_no_internet_service',
       'streaming_movies_yes', 'internet_service_type_fiber_optic',
       'internet_service_type_none']

In [26]:
# make the decision tree object
dt_3 = DecisionTreeClassifier()
# fit the data to the dt object
dt_3.fit(train[X_cols_c], train[y_col])
# predict with the dt object
dt_3_preds = dt_3.predict(train[X_cols_c])

In [27]:
print(classification_report(train[y_col], dt_3_preds))
print()
print(confusion_matrix(train[y_col], dt_3_preds))

              precision    recall  f1-score   support

           0       0.76      0.93      0.84      2897
           1       0.52      0.20      0.29      1046

    accuracy                           0.74      3943
   macro avg       0.64      0.57      0.57      3943
weighted avg       0.70      0.74      0.69      3943


[[2699  198]
 [ 834  212]]


In [28]:
# create the random forest classifier object
rf_3 = RandomForestClassifier()
# fit the rf object
rf_3.fit(train[X_cols_c], train[y_col])
# predict with the rf object
rf_3_preds = rf_3.predict(train[X_cols_c])

In [29]:
print(classification_report(train[y_col], rf_3_preds))
print()
print(confusion_matrix(train[y_col], rf_3_preds))

              precision    recall  f1-score   support

           0       0.76      0.93      0.84      2897
           1       0.52      0.20      0.29      1046

    accuracy                           0.74      3943
   macro avg       0.64      0.57      0.57      3943
weighted avg       0.70      0.74      0.69      3943


[[2699  198]
 [ 834  212]]


In [30]:
# create the K_Nearest_Neighbors object
knn_3 = KNeighborsClassifier()
# fit the KNN object
knn_3.fit(train[X_cols_c], train[y_col])
# predict with the knn object
knn_3_preds = knn_3.predict(train[X_cols_c])

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [31]:
print(classification_report(train[y_col], knn_3_preds))
print()
print(confusion_matrix(train[y_col], knn_3_preds))

              precision    recall  f1-score   support

           0       0.74      0.97      0.84      2897
           1       0.45      0.08      0.13      1046

    accuracy                           0.73      3943
   macro avg       0.60      0.52      0.49      3943
weighted avg       0.67      0.73      0.65      3943


[[2801   96]
 [ 966   80]]


In [32]:
# create the logistic regression object
lr_3 = LogisticRegression()
# fit the lr object
lr_3.fit(train[X_cols_c], train[y_col])
# predict with the lr object
lr_3_preds = lr_3.predict(train[X_cols_c])

In [33]:
print(classification_report(train[y_col], lr_3_preds))
print()
print(confusion_matrix(train[y_col], lr_3_preds))

              precision    recall  f1-score   support

           0       0.76      0.93      0.84      2897
           1       0.52      0.20      0.29      1046

    accuracy                           0.74      3943
   macro avg       0.64      0.57      0.57      3943
weighted avg       0.70      0.74      0.69      3943


[[2699  198]
 [ 834  212]]


In [34]:
X_cols_d = ['gender_male', 'multiple_lines_no_phone_service',
       'multiple_lines_yes', 'online_security_no_internet_service',
       'online_security_yes', 'online_backup_no_internet_service',
       'online_backup_yes', 'device_protection_no_internet_service',
       'device_protection_yes', 'tech_support_no_internet_service',
       'tech_support_yes', 'streaming_tv_no_internet_service',
       'streaming_tv_yes', 'streaming_movies_no_internet_service',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check']

In [35]:
# make the decision tree object
dt_4 = DecisionTreeClassifier()
# fit the data to the dt object
dt_4.fit(train[X_cols_d], train[y_col])
# predict with the dt object
dt_4_preds = dt_4.predict(train[X_cols_d])

In [36]:
print(classification_report(train[y_col], dt_4_preds))
print()
print(confusion_matrix(train[y_col], dt_4_preds))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      2897
           1       0.77      0.70      0.73      1046

    accuracy                           0.87      3943
   macro avg       0.83      0.81      0.82      3943
weighted avg       0.86      0.87      0.86      3943


[[2682  215]
 [ 316  730]]


In [37]:
# create the random forest classifier object
rf_4 = RandomForestClassifier()
# fit the rf object
rf_4.fit(train[X_cols_d], train[y_col])
# predict with the rf object
rf_4_preds = rf_4.predict(train[X_cols_d])

print(classification_report(train[y_col], rf_4_preds))
print()
print(confusion_matrix(train[y_col], rf_4_preds))

              precision    recall  f1-score   support

           0       0.91      0.90      0.91      2897
           1       0.74      0.76      0.75      1046

    accuracy                           0.87      3943
   macro avg       0.83      0.83      0.83      3943
weighted avg       0.87      0.87      0.87      3943


[[2612  285]
 [ 246  800]]


In [38]:
# create the K_Nearest_Neighbors object
knn_4 = KNeighborsClassifier()
# fit the KNN object
knn_4.fit(train[X_cols_d], train[y_col])
# predict with the knn object
knn_4_preds = knn_4.predict(train[X_cols_d])

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [39]:
print(classification_report(train[y_col], knn_4_preds))
print()
print(confusion_matrix(train[y_col], knn_4_preds))

              precision    recall  f1-score   support

           0       0.86      0.88      0.87      2897
           1       0.64      0.59      0.61      1046

    accuracy                           0.80      3943
   macro avg       0.75      0.73      0.74      3943
weighted avg       0.80      0.80      0.80      3943


[[2554  343]
 [ 433  613]]


In [40]:
# create the logistic regression object
lr_4 = LogisticRegression()
# fit the lr object
lr_4.fit(train[X_cols_d], train[y_col])
# predict with the lr object
lr_4_preds = lr_4.predict(train[X_cols_d])

In [41]:
print(classification_report(train[y_col], lr_4_preds))
print()
print(confusion_matrix(train[y_col], lr_4_preds))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      2897
           1       0.61      0.52      0.56      1046

    accuracy                           0.78      3943
   macro avg       0.72      0.70      0.71      3943
weighted avg       0.77      0.78      0.78      3943


[[2547  350]
 [ 503  543]]


In [42]:
rf_4_preds_val = rf_4.predict(validate[X_cols_d])

print(classification_report(validate[y_col], rf_4_preds_val))
print()
print(confusion_matrix(validate[y_col], rf_4_preds_val))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      1242
           1       0.56      0.54      0.55       449

    accuracy                           0.76      1691
   macro avg       0.70      0.69      0.69      1691
weighted avg       0.76      0.76      0.76      1691


[[1051  191]
 [ 208  241]]


In [43]:
def create_classification_models(X_cols, y_col):
    # make the decision tree object
    dt = DecisionTreeClassifier()
    # fit the data to the dt object
    dt.fit(train[X_cols], train[y_col])
    # predict with the dt object
    dt_preds = dt.predict(train[X_cols])
    dt_val_preds = dt.predict(validate[X_cols])
    print('decision tree')
    print(classification_report(train[y_col], dt_preds))
    print()
    print(confusion_matrix(train[y_col], dt_preds))
    print('----------validation data----------')
    print(classification_report(validate[y_col], dt_val_preds))
    print()
    print(confusion_matrix(validate[y_col], dt_val_preds))
    print('\n\n')
    
    # create the random forest classifier object
    rf = RandomForestClassifier()
    # fit the rf object
    rf.fit(train[X_cols], train[y_col])
    # predict with the rf object
    rf_preds = rf.predict(train[X_cols])
    rf_val_preds = rf.predict(validate[X_cols])
    print('random forest')
    print(classification_report(train[y_col], rf_preds))
    print()
    print(confusion_matrix(train[y_col], rf_preds))
    print('----------validation data----------')
    print(classification_report(validate[y_col], rf_val_preds))
    print()
    print(confusion_matrix(validate[y_col], rf_val_preds))
    print('\n\n')
    
    # create the K_Nearest_Neighbors object
    knn = KNeighborsClassifier()
    # fit the KNN object
    knn.fit(train[X_cols], train[y_col])
    # predict with the knn object
    knn_preds = knn.predict(train[X_cols])
    knn_val_preds = knn.predict(validate[X_cols])
    print('k nearest neighbors')
    print(classification_report(train[y_col], knn_preds))
    print()
    print(confusion_matrix(train[y_col], knn_preds))
    print('----------validation data----------')
    print(classification_report(validate[y_col], knn_val_preds))
    print()
    print(confusion_matrix(validate[y_col], knn_val_preds))
    print('\n\n')
    
    # create the logistic regression object
    lr = LogisticRegression()
    # fit the lr object
    lr.fit(train[X_cols], train[y_col])
    # predict with the lr object
    lr_preds = lr.predict(train[X_cols])
    lr_val_preds = lr.predict(validate[X_cols])
    print('logistic regression')
    print(classification_report(train[y_col], lr_preds))
    print()
    print(confusion_matrix(train[y_col], lr_preds))
    print('----------validation data----------')
    print(classification_report(validate[y_col], lr_val_preds))
    print()
    print(confusion_matrix(validate[y_col], lr_val_preds))

In [44]:
create_classification_models(X_cols_d, y_col)

decision tree
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      2897
           1       0.77      0.70      0.73      1046

    accuracy                           0.87      3943
   macro avg       0.83      0.81      0.82      3943
weighted avg       0.86      0.87      0.86      3943


[[2682  215]
 [ 316  730]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.82      0.83      0.82      1242
           1       0.51      0.50      0.50       449

    accuracy                           0.74      1691
   macro avg       0.66      0.66      0.66      1691
weighted avg       0.74      0.74      0.74      1691


[[1026  216]
 [ 226  223]]



random forest
              precision    recall  f1-score   support

           0       0.91      0.90      0.91      2897
           1       0.74      0.76      0.75      1046

    accuracy                           0.87      3943
   ma

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

k nearest neighbors
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      2897
           1       0.64      0.59      0.61      1046

    accuracy                           0.80      3943
   macro avg       0.75      0.73      0.74      3943
weighted avg       0.80      0.80      0.80      3943


[[2554  343]
 [ 433  613]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.82      0.84      0.83      1242
           1       0.52      0.49      0.50       449

    accuracy                           0.75      1691
   macro avg       0.67      0.66      0.67      1691
weighted avg       0.74      0.75      0.74      1691


[[1041  201]
 [ 230  219]]



logistic regression
              precision    recall  f1-score   support

           0       0.84      0.88      0.86      2897
           1       0.61      0.52      0.56      1046

    accuracy                           0.78    

In [45]:
X_cols_e = ['senior_citizen', 'partner', 'dependents',
       'gender_male', 'multiple_lines_no_phone_service',
       'multiple_lines_yes', 'online_security_yes', 'online_backup_yes',
       'device_protection_yes', 'tech_support_yes', 'streaming_tv_yes',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check']

In [46]:
create_classification_models(X_cols_e, y_col)

decision tree
              precision    recall  f1-score   support

           0       0.92      0.96      0.94      2897
           1       0.89      0.78      0.83      1046

    accuracy                           0.92      3943
   macro avg       0.91      0.87      0.89      3943
weighted avg       0.92      0.92      0.91      3943


[[2795  102]
 [ 227  819]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.80      0.83      0.81      1242
           1       0.48      0.45      0.46       449

    accuracy                           0.72      1691
   macro avg       0.64      0.64      0.64      1691
weighted avg       0.72      0.72      0.72      1691


[[1025  217]
 [ 249  200]]



random forest
              precision    recall  f1-score   support

           0       0.94      0.95      0.94      2897
           1       0.85      0.83      0.84      1046

    accuracy                           0.92      3943
   ma

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

k nearest neighbors
              precision    recall  f1-score   support

           0       0.86      0.90      0.88      2897
           1       0.69      0.61      0.65      1046

    accuracy                           0.83      3943
   macro avg       0.78      0.76      0.77      3943
weighted avg       0.82      0.83      0.82      3943


[[2617  280]
 [ 409  637]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1242
           1       0.51      0.47      0.49       449

    accuracy                           0.74      1691
   macro avg       0.66      0.65      0.66      1691
weighted avg       0.73      0.74      0.73      1691


[[1036  206]
 [ 238  211]]



logistic regression
              precision    recall  f1-score   support

           0       0.84      0.89      0.86      2897
           1       0.62      0.52      0.57      1046

    accuracy                           0.79    

In [47]:
create_classification_models(X_cols_d, y_col)

decision tree
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      2897
           1       0.77      0.70      0.73      1046

    accuracy                           0.87      3943
   macro avg       0.83      0.81      0.82      3943
weighted avg       0.86      0.87      0.86      3943


[[2682  215]
 [ 316  730]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.82      0.83      0.82      1242
           1       0.51      0.50      0.51       449

    accuracy                           0.74      1691
   macro avg       0.67      0.66      0.67      1691
weighted avg       0.74      0.74      0.74      1691


[[1030  212]
 [ 225  224]]



random forest
              precision    recall  f1-score   support

           0       0.91      0.91      0.91      2897
           1       0.74      0.75      0.75      1046

    accuracy                           0.87      3943
   ma

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

k nearest neighbors
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      2897
           1       0.64      0.59      0.61      1046

    accuracy                           0.80      3943
   macro avg       0.75      0.73      0.74      3943
weighted avg       0.80      0.80      0.80      3943


[[2554  343]
 [ 433  613]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.82      0.84      0.83      1242
           1       0.52      0.49      0.50       449

    accuracy                           0.75      1691
   macro avg       0.67      0.66      0.67      1691
weighted avg       0.74      0.75      0.74      1691


[[1041  201]
 [ 230  219]]



logistic regression
              precision    recall  f1-score   support

           0       0.84      0.88      0.86      2897
           1       0.61      0.52      0.56      1046

    accuracy                           0.78    

In [48]:
X_cols_f = ['gender_male', 'multiple_lines_no_phone_service',
            'senior_citizen', 'partner',
       'multiple_lines_yes',
       'online_security_yes',
       'online_backup_yes',
       'device_protection_yes',
       'tech_support_yes',
       'streaming_tv_yes',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check']

In [49]:
create_classification_models(X_cols_f, y_col)

decision tree
              precision    recall  f1-score   support

           0       0.91      0.96      0.94      2897
           1       0.88      0.74      0.81      1046

    accuracy                           0.91      3943
   macro avg       0.90      0.85      0.87      3943
weighted avg       0.90      0.91      0.90      3943


[[2794  103]
 [ 267  779]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.80      0.83      0.82      1242
           1       0.48      0.42      0.45       449

    accuracy                           0.72      1691
   macro avg       0.64      0.63      0.63      1691
weighted avg       0.71      0.72      0.72      1691


[[1034  208]
 [ 259  190]]



random forest
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      2897
           1       0.84      0.79      0.82      1046

    accuracy                           0.91      3943
   ma

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

k nearest neighbors
              precision    recall  f1-score   support

           0       0.86      0.89      0.88      2897
           1       0.66      0.61      0.64      1046

    accuracy                           0.81      3943
   macro avg       0.76      0.75      0.76      3943
weighted avg       0.81      0.81      0.81      3943


[[2569  328]
 [ 405  641]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1242
           1       0.49      0.47      0.48       449

    accuracy                           0.73      1691
   macro avg       0.65      0.65      0.65      1691
weighted avg       0.73      0.73      0.73      1691


[[1027  215]
 [ 240  209]]



logistic regression
              precision    recall  f1-score   support

           0       0.84      0.89      0.86      2897
           1       0.62      0.52      0.57      1046

    accuracy                           0.79    

In [50]:
X_cols_g = ['gender_male', 'multiple_lines_no_phone_service',
       'multiple_lines_yes',
       'online_security_yes',
       'online_backup_yes',
       'device_protection_yes', 
       'tech_support_yes',
       'streaming_tv_yes',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check']

In [51]:
create_classification_models(X_cols_g, y_col)

decision tree
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      2897
           1       0.77      0.70      0.73      1046

    accuracy                           0.87      3943
   macro avg       0.83      0.81      0.82      3943
weighted avg       0.86      0.87      0.86      3943


[[2682  215]
 [ 316  730]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.82      0.83      0.82      1242
           1       0.51      0.50      0.51       449

    accuracy                           0.74      1691
   macro avg       0.67      0.66      0.67      1691
weighted avg       0.74      0.74      0.74      1691


[[1029  213]
 [ 225  224]]



random forest
              precision    recall  f1-score   support

           0       0.91      0.91      0.91      2897
           1       0.74      0.75      0.75      1046

    accuracy                           0.87      3943
   ma

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

k nearest neighbors
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      2897
           1       0.65      0.55      0.60      1046

    accuracy                           0.80      3943
   macro avg       0.75      0.72      0.73      3943
weighted avg       0.79      0.80      0.80      3943


[[2581  316]
 [ 466  580]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.82      0.85      0.83      1242
           1       0.53      0.49      0.51       449

    accuracy                           0.75      1691
   macro avg       0.68      0.67      0.67      1691
weighted avg       0.74      0.75      0.75      1691


[[1050  192]
 [ 230  219]]



logistic regression
              precision    recall  f1-score   support

           0       0.84      0.88      0.86      2897
           1       0.61      0.52      0.56      1046

    accuracy                           0.78    

In [52]:
X_cols_h = ['multiple_lines_no_phone_service', 'dependents',
       'multiple_lines_yes', 'online_security_yes',
       'online_backup_yes', 'device_protection_yes', 
       'tech_support_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check']

In [53]:
X_list = [X_cols_a, X_cols_b, X_cols_c, X_cols_d, X_cols_e, X_cols_f, X_cols_g, X_cols_h]
for X in X_list:
    lr = LogisticRegression()
    lr.fit(train[X], train[y_col])
    pred = lr.predict(train[X])
    val_pred = lr.predict(validate[X])
    print(f'train recall score is: {recall_score(train[y_col], pred):.2%}')
    print(f'train accuracy score is: {accuracy_score(train[y_col], pred):.2%}')
    print(f'val recall score is: {recall_score(validate[y_col], val_pred):.2%}')
    print(f'val accuracy score is: {accuracy_score(validate[y_col], val_pred):.2%}')
    print()

train recall score is: 37.86%
train accuracy score is: 75.68%
val recall score is: 39.20%
val accuracy score is: 75.75%

train recall score is: 38.15%
train accuracy score is: 77.23%
val recall score is: 36.30%
val accuracy score is: 76.23%

train recall score is: 20.27%
train accuracy score is: 73.83%
val recall score is: 20.27%
val accuracy score is: 72.62%

train recall score is: 51.91%
train accuracy score is: 78.37%
val recall score is: 55.23%
val accuracy score is: 79.07%

train recall score is: 52.29%
train accuracy score is: 78.95%
val recall score is: 52.12%
val accuracy score is: 78.00%

train recall score is: 52.20%
train accuracy score is: 79.00%
val recall score is: 51.22%
val accuracy score is: 77.71%

train recall score is: 51.91%
train accuracy score is: 78.37%
val recall score is: 55.23%
val accuracy score is: 79.07%

train recall score is: 51.05%
train accuracy score is: 78.62%
val recall score is: 54.12%
val accuracy score is: 79.07%



In [54]:
test_pred = lr.predict(test[X_cols_h])
print(f'test recall score is: {recall_score(test[y_col], test_pred):.2%}')
print(classification_report(test[y_col], test_pred))

test recall score is: 50.27%
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1035
           1       0.64      0.50      0.56       374

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409



In [55]:
create_classification_models(X_cols_h, y_col)

decision tree
              precision    recall  f1-score   support

           0       0.88      0.89      0.88      2897
           1       0.68      0.66      0.67      1046

    accuracy                           0.83      3943
   macro avg       0.78      0.77      0.78      3943
weighted avg       0.83      0.83      0.83      3943


[[2574  323]
 [ 356  690]]
----------validation data----------
              precision    recall  f1-score   support

           0       0.84      0.84      0.84      1242
           1       0.55      0.57      0.56       449

    accuracy                           0.76      1691
   macro avg       0.70      0.70      0.70      1691
weighted avg       0.77      0.76      0.76      1691


[[1038  204]
 [ 195  254]]



random forest
              precision    recall  f1-score   support

           0       0.89      0.87      0.88      2897
           1       0.67      0.70      0.68      1046

    accuracy                           0.83      3943
   ma

/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

In [56]:
# create a list of columns to be used as the ML model parameters 
X_cols = ['multiple_lines_no_phone_service', 'dependents',
           'multiple_lines_yes', 'online_security_yes',
           'online_backup_yes', 'device_protection_yes', 
           'tech_support_yes', 'contract_type_one_year',
           'contract_type_two_year', 'internet_service_type_fiber_optic',
           'internet_service_type_none', 'payment_type_credit_card_automatic',
           'payment_type_electronic_check', 'payment_type_mailed_check']
# create a variable for the column used as the prediction target of the ML models
y_col = 'churn'

In [57]:
def model_prep(train, validate, test):
    '''
    This function will take in train, validate and test DataFrames and return 
    DataFrames that contain the columns to be used with the ML models.
    '''
    # create new dataframes with the desired columns
    train_X = train[X_cols]
    validate_X = validate[X_cols]
    test_X = test[X_cols]
    train_y = train[y_col]
    validate_y = validate[y_col]
    test_y = test[y_col]
    # return the new dataframes
    return train_X, validate_X, test_X, train_y, validate_y, test_y

In [58]:
train_X, validate_X, test_X, train_y, validate_y, test_y = model_prep(train,validate,test)

In [59]:
def get_decision_tree(train_X, validate_X, train_y, validate_y):
    '''
    This function will use a decision tree machine learning model to predict 
    customer churn using the columns chosen during the exploration process.
    '''
    # make the decision tree object
    dt = DecisionTreeClassifier()
    # fit the data to the dt object
    dt.fit(train_X, train_y)
    # predict with the dt object
    dt_preds = dt.predict(train_X)
    dt_val_preds = dt.predict(validate_X)
    # "Model Type" 
    # "evaluation metric" on train: "evaluation result" 
    # "evaluation metric" on validate: "evaluation result"
    print('Decision Tree Model')
    print(f'Recall score on train: {recall_score(train_y, dt_preds):.2%}')
    print(f'Recall score on validate: {recall_score(validate_y, dt_val_preds):.2%}')
    # return the decision tree model for use in other functions
    return dt

In [60]:
dt = get_decision_tree(train_X, validate_X, train_y, validate_y)

Decision Tree Model
Recall score on train: 65.97%
Recall score on validate: 56.35%


In [61]:
def get_random_forest(train_X, validate_X, train_y, validate_y):
    '''
    This function will use a random forest machine learning model to predict 
    customer churn using the columns chosen during the exploration process.
    '''
    # make the decision tree object
    rf = RandomForestClassifier()
    # fit the data to the rf object
    rf.fit(train_X, train_y)
    # predict with the rf object
    rf_preds = rf.predict(train_X)
    rf_val_preds = rf.predict(validate_X)
    # "Model Type" 
    # "evaluation metric" on train: "evaluation result" 
    # "evaluation metric" on validate: "evaluation result"
    print('Random Forest Model')
    print(f'Recall score on train: {recall_score(train_y, rf_preds):.2%}')
    print(f'Recall score on validate: {recall_score(validate_y, rf_val_preds):.2%}')
    # return the random forest model for use in other functions
    return rf

In [62]:
rf = get_random_forest(train_X, validate_X, train_y, validate_y)

Random Forest Model
Recall score on train: 69.98%
Recall score on validate: 57.68%


In [63]:
def get_logistic_regression(train_X, validate_X, train_y, validate_y):
    '''
    This function will use a logistic regression machine learning model to predict 
    customer churn using the columns chosen during the exploration process.
    '''
    # make the decision tree object
    lr = LogisticRegression()
    # fit the data to the lr object
    lr.fit(train_X, train_y)
    # predict with the lr object
    lr_preds = lr.predict(train_X)
    lr_val_preds = lr.predict(validate_X)
    # "Model Type" 
    # "evaluation metric" on train: "evaluation result" 
    # "evaluation metric" on validate: "evaluation result"
    print('Logistic Regression Model')
    print(f'Recall score on train: {recall_score(train_y, lr_preds):.2%}')
    print(f'Recall score on validate: {recall_score(validate_y, lr_val_preds):.2%}')
    # return the logistic regression model for use in other functions
    return lr

In [64]:
lr = get_logistic_regression(train_X, validate_X, train_y, validate_y)

Logistic Regression Model
Recall score on train: 51.05%
Recall score on validate: 54.12%


In [65]:
def get_rf_test(test_X, test_y, rf):
    '''
    This function will take in a random forest model in order to predict customer
    churn rate using the test data.
    '''
    # make a prediction using the test data and passed rf model
    rf_test_preds = rf.predict(test_X)
    # print the recall score for the test data
    print('Random Forest Model')
    print(f'Recall score on test: {recall_score(test_y, rf_test_preds):.2%}')

In [66]:
get_rf_test(test_X, test_y, rf)

Random Forest Model
Recall score on test: 54.28%


In [67]:
predictions = pd.concat([
    pd.DataFrame(test.customer_id).reset_index().drop(columns='index'),
    pd.DataFrame(test_pred).rename(columns={0:'prediction_of_churn'}),
    pd.DataFrame(lr.predict_proba(
        test[X_cols])).drop(columns=0).rename(
        columns={1:'probability_of_churn'})
],axis=1)
predictions

customer_id  prediction_of_churn  probability_of_churn
0     2851-MMUTZ                    0              0.208817
1     4257-GAESD                    0              0.391255
2     2688-BHGOG                    1              0.672918
3     7005-CYUIL                    0              0.049591
4     2228-BZDEE                    0              0.018534
...          ...                  ...                   ...
1404  5480-TBGPH                    0              0.411255
1405  1098-TDVUQ                    0              0.157289
1406  2486-WYVVE                    0              0.100380
1407  5076-YVXCM                    1              0.581098
1408  0374-AACSZ                    0              0.351294

[1409 rows x 3 columns]

In [68]:
# predictions.to_csv('predictions.csv')

In [74]:
rf_preds = pd.Series(rf.predict(train_X))

In [78]:
train = train.reset_index()

In [87]:
prediction_customers = train[rf_preds == 1]

In [85]:
internet

customer_id  gender  senior_citizen  partner  dependents  tenure  \
5717  8050-XGRVL  Female               0        1           1      62   
1083  1576-PFZIW    Male               1        1           0      70   
2475  3541-ZNUHK  Female               0        1           1      55   
2350  3370-GQEAL    Male               0        1           1      30   
2393  3422-LYEPQ    Male               0        1           1       1   
...          ...     ...             ...      ...         ...     ...   
4128  5839-SUYVZ    Male               0        0           0      16   
731   1078-TDCRN  Female               1        1           0       3   
2272  3249-VHRIP  Female               0        0           0      62   
6629  9419-IPPBE  Female               0        1           1      51   
5563  7838-LAZFO    Male               0        1           0      45   

      phone_service    multiple_lines online_security online_backup  ...  \
5717              1                No             Yes            No  ...   
1083              1                No             Yes           Yes  ...   
2475              1               Yes             Yes           Yes  ...   
2350              1               Yes              No            No  ...   
2393              1                No              No            No  ...   
...             ...               ...             ...           ...  ...   
4128              1                No              No            No  ...   
731               0  No phone service              No           Yes  ...   
2272              0  No phone service              No           Yes  ...   
6629              1               Yes              No            No  ...   
5563              1                No             Yes           Yes  ...   

     streaming_movies_no_internet_service streaming_movies_yes  \
5717                                    0                    0   
1083                                    0                    1   
2475                                    0                    0   
2350                                    0                    0   
2393                                    0                    0   
...                                   ...                  ...   
4128                                    0                    0   
731                                     0                    0   
2272                                    0                    1   
6629                                    0                    1   
5563                                    0                    1   

     contract_type_one_year contract_type_two_year  \
5717                      1                      0   
1083                      0                      1   
2475                      0                      0   
2350                      0                      0   
2393                      0                      0   
...                     ...                    ...   
4128                      0                      0   
731                       0                      0   
2272                      0                      1   
6629                      1                      0   
5563                      1                      0   

      internet_service_type_fiber_optic  internet_service_type_none  \
5717                                  0                           0   
1083                                  1                           0   
2475                                  1                           0   
2350                                  1                           0   
2393                                  1                           0   
...                                 ...                         ...   
4128                                  1                           0   
731                                   0                           0   
2272                                  0                           0   
6629                                  1                        

In [83]:
prediction_customers

index customer_id  gender  senior_citizen  partner  dependents  tenure  \
7      2393  3422-LYEPQ    Male               0        1           1       1   
11     5509  7758-XKCBS    Male               0        0           0      15   
13     2987  4282-ACRXS    Male               1        1           0      38   
20     2361  3384-CTMSF    Male               0        1           0      47   
23     3894  5480-HPRRX  Female               1        0           0       3   
...     ...         ...     ...             ...      ...         ...     ...   
3929   1966  2845-HSJCY  Female               0        1           1      14   
3932   1688  2460-NGXBJ    Male               1        1           1      11   
3934   4940  6959-UWKHF    Male               0        0           0       1   
3937   3009  4307-KTUMW    Male               0        1           0      53   
3939    731  1078-TDCRN  Female               1        1           0       3   

      phone_service    multiple_lines online_security  ...  \
7                 1                No              No  ...   
11                0  No phone service              No  ...   
13                0  No phone service              No  ...   
20                1               Yes              No  ...   
23                0  No phone service              No  ...   
...             ...               ...             ...  ...   
3929              1               Yes              No  ...   
3932              1               Yes              No  ...   
3934              1                No              No  ...   
3937              1               Yes             Yes  ...   
3939              0  No phone service              No  ...   

     contract_type_one_year contract_type_two_year  \
7                         0                      0   
11                        0                      0   
13                        0                      0   
20                        0                      0   
23                        0                      0   
...                     ...                    ...   
3929                      0                      0   
3932                      0                      0   
3934                      0                      0   
3937                      0                      0   
3939                      0                      0   

     internet_service_type_fiber_optic internet_service_type_none  \
7                                    1                          0   
11                                   0                          0   
13                                   0                          0   
20                                   1                          0   
23                                   0                          0   
...                                ...                        ...   
3929                                 1                          0   
3932                                 1                          0   
3934                                 0                          0   
3937                                 1                          0   
3939                                 0                          0   

     payment_type_credit_card_automatic  payment_type_electronic_check  \
7                                     0                              1   
11                                    0                              1   
13                                    0                              1   
20                                    0                              1   
23                                    0                              1   
...                                 ...                            ...   
3929                                  0                              1   
3932                                  1                              0   
3934                                  0                              1   
3937                                  0                              1   
3939    

In [94]:
no_service = ((prediction_customers.online_backup == 'No') &
                          (prediction_customers.online_security == 'No') &
                         (prediction_customers.device_protection == 'No'))

In [95]:
len(prediction_customers[no_service]) / len(prediction_customers)

0.46855059252506837